export const productLocators={
       productMenu:'xpath=//a[contains(text(), "Products")]',
       allProductsPageTitle:'xpath=//h2[contains(text(), "All Products")]',
       productsList:"xpath=//div[@class='single-products']",
       productsPageProductTitles:"xpath=//div[@class='productinfo text-center']/p",
       viewProductButtons:"xpath=//a[contains(text(), 'View Product')]",
       productsDetailsTitle:"xpath=//div[@class='product-information']/h2",
       productsDetailsProductsPrice:"xpath=//div[@class='product-information']/span",
       productsDetailsProductInformations:"xpath=//div[@class='product-information']/p",
       searchProductField:"xpath=//input[@id='search_product']",
       searchButton:"xpath=//button[@id='submit_search']",
       womenCategoryLink:"xpath=//a[@data-parent='#accordian' and @href='#Women']",
       topsSubCategoryLink:"xpath=(//a[contains(text(), 'Tops')])[1]",
       productsCategoryPageTitle:"xpath=//h2[@class='title text-center']",
       firstProductAddToCartButton:"xpath=(//a[@data-product-id='1'])[1]",
       productInfoTitles:"xpath=//div[@class='productinfo text-center']/p",
       productInfoPrices:"xpath=//div[@class='productinfo text-center']/h2",
       secondProductAddToCartButton:"xpath=(//a[@data-product-id='2'])[1]",
       productAddedToCartSuccessMessage:"xpath=(//div[@class='modal-body']//p)[1]",
       continueShoppingButton:"xpath=//div[@class='modal-footer']/button"
}